### ISSUE TITLE
Change electron-auto-updater to electron-updater

### ISSUE THREAD

**Issue by SirWindfield** [RekkyRek/droppl#3]
Seems like the first package is deprecated.

*Edit:*
It would be worth it to consider [electron-builder](https://github.com/electron-userland/electron-builder) for bundling the Torrent Client. It is basically the up-to-date version of electron-auto-updater.

**Comment by SirWindfield** [comment]
It would be worth it to consider [electron-builder](https://github.com/electron-userland/electron-builder) for bundling the Torrent Client. It is basically the up-to-date version of electron-auto-updater.

**Comment by RekkyRek** [comment]
i think i'm actually gonna use https://github.com/electron/windows-installer for building

**Comment by SirWindfield** [comment]
Isn't your app cross platform?

**Comment by RekkyRek** [comment]
Yes, good point xD The installer doesn't look as nice though.

**Comment by SirWindfield** [comment]
Setting up electron-builder is quite easy tho :smile:

**Comment by RekkyRek** [comment]
Will take a look when i come home.

**Comment by SirWindfield** [comment]
#7
