### ISSUE TITLE
jQuery package is deprecated, use jquery instead.

### ISSUE THREAD

**Issue by SirWindfield** [RekkyRek/droppl#4]
Looks like the module's name now is `jquery`. If we already are discussing `package.json`, isn't `vue` available there too? Why did you use `vue.min.js`?

**Comment by RekkyRek** [comment]
When using the npm version of vue it seems that you can't compile templates. https://vuejs.org/v2/guide/installation.html#Runtime-Compiler-vs-Runtime-only

**Comment by RekkyRek** [comment]
https://github.com/RekkyRek/droppl/commit/4194d81a70092dea86399c032d039821b2f6119b
