### ISSUE TITLE
Getting error pasting magnet link

### ISSUE THREAD

**Issue by SirWindfield** [RekkyRek/droppl#6]
Link: `magnet:?xt=urn:sha1:0b834a7c3adb917a47d866197b54b99926b256dd&dn=OOo_2.1.0_Win32Intel_install_en-US.exe&xs=http://mirror.switch.ch/ftp/mirror/OpenOffice/stable/2.1.0/OOo_2.1.0_Win32Intel_install_en-US.exe`

_Error message_:

Download the Vue Devtools extension for a better development experience:
https://github.com/vuejs/vue-devtools
You are running Vue in development mode.
Make sure to turn on production mode when deploying for production.
See more tips at https://vuejs.org/guide/deployment.html
Uncaught Error: Could not call remote function ''. Check that the function signature is correct. Underlying error: Invalid torrent identifier
Error: Could not call remote function ''. Check that the function signature is correct. Underlying error: Invalid torrent identifier
    at callFunction (D:\Data\Projects\droppl\node_modules\electron\dist\resources\electron.asar\browser\rpc-server.js:235:11)
    at EventEmitter.<anonymous> (D:\Data\Projects\droppl\node_modules\electron\dist\resources\electron.asar\browser\rpc-server.js:342:5)
    at emitMany (events.js:127:13)
    at EventEmitter.emit (events.js:201:7)
    at WebContents.<anonymous> (D:\Data\Projects\droppl\node_modules\electron\dist\resources\electron.asar\browser\api\web-contents.js:231:13)
    at emitTwo (events.js:106:13)
    at WebContents.emit (events.js:191:7)
metaToValue	@	D:\Data\Projects\droppl\node_modules\electron\dist\resources\electron.asar\renderer\api\remote.js:217

remoteMemberFunction	@	D:\Data\Projects\droppl\node_modules\electron\dist\resources\electron.asar\renderer\api\remote.js:113

(anonymous function)	@	mainApp.js:173

dispatch	@	D:\Data\Projects\droppl\node_modules\jQuery\lib\node-jquery.js:3357

eventHandle	@	D:\Data\Projects\droppl\node_modules\jQuery\lib\node-jquery.js:2966

**Comment by RekkyRek** [comment]
Is this reproducible? If so please tell me how. It seems that the renderer couldn't find the main function. Will look into it.

**Comment by RekkyRek** [comment]
I successfully reproduced it on my Linux laptop. What OS are you running?

**Comment by RekkyRek** [comment]
From my conclusion it seems the magnet doesn't have enough information to initialize the torrent.

**Comment by SirWindfield** [comment]
I am running Windows. I tried it with the OpenOffice magnet link
