### ISSUE TITLE
Sooo... how to download and use on Mac? Links don't work

### ISSUE THREAD

**Issue by idchlife** [RekkyRek/droppl#8]

**Comment by SirWindfield** [comment]
WIll do it later on :smile:

**Comment by RekkyRek** [comment]
I am way to poor to afford a mac nor do i know anyone with a mac, so testing and all that stuff is a bit hard...

**Comment by RekkyRek** [comment]
The current build is most likely not bug free on mac

**Comment by RekkyRek** [comment]
If you want to try it you can clone the repo, run npm install then electron . in the console
