### ISSUE TITLE
Travis Failing

### ISSUE THREAD

**Issue by RekkyRek** [RekkyRek/droppl#9]
Travis builds are failing and i have no idea how Travis works, @SirWindfield?

**Comment by SirWindfield** [comment]
Lemme check

**Comment by RekkyRek** [comment]
Ah, i changed that in my latest unpushed code yesterday. I madenit into if node_env instead.

**Comment by SirWindfield** [comment]
Ye, I created a new branch too :D It should work again if you just push your change to master.
